events {}

http {
    upstream tomcat_server {
        server host.docker.internal:8080;  # Or actual IP like 192.168.1.100:8080
    }

    server {
        listen 80;
        server_name trialc5.qualcy.net;

        # Redirect HTTP to HTTPS
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        server_name trialc5.qualcy.net;

		ssl_certificate /etc/ssl/qualcy/fullchain.pem;
		ssl_certificate_key /etc/ssl/qualcy/privkey.pem;
	
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;

        location / {
            proxy_pass http://tomcat_server;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
