spring.application.name=qualcy
server.port=3050
spring.mvc.static-path-pattern=/resources/**
onlyoffice.jwt.secret=abq3EH95CcmsYqrz5voHdGJkxCRqm0fE
server.servlet.context-path=/docsmanager
onlyoffice.service.base.url = https://trialc6.qualcy.net/docsmanager/
#onlyoffice.callback.url=http://13.204.49.246:8080/docsmanager/save?filename=
#onlyoffice.download.url=http://13.204.49.246:8080/docsmanager/files/
onlyoffice.storage.path=data/images/uploadLogosFiles/Model4/AttachedFiles
onlyoffice.edit.message = This document is currently being edited by %s. Please try again later.
onlyoffice.docserver.url=http://localhost