spring.profiles.active=uat
# Ensure NoHandlerFoundException reaches @ExceptionHandler instead of default 404 page
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false