spring.application.name=qualcy
server.port=3050
spring.mvc.static-path-pattern=/resources/**
onlyoffice.jwt.secret=abq3EH95CcmsYqrz5voHdGJkxCRqm0fE
onlyoffice.callback.url=http://13.204.49.246:3050/save?filename=
onlyoffice.storage.path=data			  
onlyoffice.docserver.url=http://localhost