spring.application.name=qualcy
server.port=8080
spring.mvc.static-path-pattern=/resources/**
onlyoffice.jwt.secret=abq3EH95CcmsYqrz5voHdGJkxCRqm0fE
spring.datasource.url=jdbc:postgresql://52.66.119.34:5432/distr
spring.datasource.username=postgres
spring.datasource.password=Sachi@2010
onlyoffice.edit.message = This document is currently being edited by %s. Please try again later.
onlyoffice.docserver.url=http://localhost