-- H2 in-memory schema for tests (MODE=PostgreSQL makes BIGSERIAL work)
CREATE TABLE IF NOT EXISTS users (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username   VARCHAR(50)  UNIQUE NOT NULL,
    password   VARCHAR(255) NOT NULL,
    full_name  VARCHAR(255),
    email      VARCHAR(255) UNIQUE,
    phone      VARCHAR(20),
    role       VARCHAR(20)  NOT NULL CHECK (role IN ('ADMIN','MANAGER','STAFF')),
    enabled    BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);
