version: '3'

services:
  nginx:
    image: nginx:alpine
    container_name: onlyoffice-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/onlyoffice.conf:/etc/nginx/conf.d/default.conf
      - ./ssl/fullchain.pem:/etc/ssl/qualcy/fullchain.pem
      - ./ssl/privkey.pem:/etc/ssl/qualcy/privkey.pem
